name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  release:
    types: [created]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ github.event_name  }}"
      - run: echo "$(if [ ${{ github.event_name }} == 'release' ]; then echo SUKA; else echo SUCA; fi)"
      - run: echo "${{ github.ref_name }}"
