name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    tags: ["*"]
  release:
    types: [created]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g csv-parser
      - run: echo "$(if [ github.event_name == 'release' && github.event.action == 'created' ]; then echo SUKA; else echo SUCA; fi)"